[NEW] New module: attachment_attach_non_editable
OCA/knowledge pull request #124
Opened 2017-02-03 14:08 UTC by LeartS

In odoo, by default, you can't add attachments to a record if the form view
is set as not editable (``edit='false'`` in the form tag)

This module adds a new form view attribute, ``attach=``, which lets you
enable attachment uploads even in non-editable forms.

2017-02-03 22:10 UTC, max3903 requested changes
Small change. 

:+1:

2017-02-03 22:10 UTC, max3903 commented on attachment_attach_non_editable/README.rst
> +
Can you add the link to Runbot?

2017-03-21 22:51 UTC, dreispt approved these changes
LGTM

2017-03-21 22:51 UTC, dreispt commented on attachment_attach_non_editable/README.rst
> +Add the ``attach=true`` attribute to the form view tag which of uneditable views
Add the quotes: ``attach="true"``

2017-03-28 14:36 UTC, hbrunn approved these changes
people probably will be disappointed because this still doesn't allow attaching attachments to records which are actually not writable for the user, because this is how Odoo checks permissions. Maybe add a line about that to the readme?

2017-09-25 09:21 UTC, LeartS commented on attachment_attach_non_editable/README.rst
> +
Should I link the runbot to the 10.0 branch (which would work once merged) or to the pull request branch (which works as long as the PR is active, but not after)? I always had this doubt

2017-09-25 09:35 UTC, LeartS commented
Addressed the comments, @max3903 can you update your review?

2017-09-25 13:48 UTC, max3903 approved these changes

2017-09-25 13:49 UTC, merged