[FIX] document_page_approval: Modify in records rules
OCA/knowledge pull request #215
Opened 2019-05-31 16:40 UTC by nicomacr

Add the the group eployee to the rule "Change Request Global" to allow to the user with the rule "Change Request Approver" to create pages

2019-05-31 17:06 UTC, max3903 commented
@nicomacr If you had a group to the rule, the rule is not global anymore and only applies to that group. This is a major change of behavior.

2019-06-19 12:21 UTC, ivantodorovich commented
I can confirm there is a bug there, that rule should definitely not be global.

To reproduce the bug on runbot: 
1. set demo user to Knowledge / Approver and try to approve a 
2. activate changes on the document category
3. create a change request using another user (ie: admin)
4. try to validate the change request using demo

The change request doesn't show because of that global rule, so it's impossible to approve.


Tested this on runbot and its fixed now :+1:
I would still change the group, though

2019-06-19 12:22 UTC, ivantodorovich requested changes

2019-06-19 12:22 UTC, ivantodorovich commented on document_page_approval/security/document_page_security.xml
> +        <field name="groups" eval="[(6, 0, [ref('base.group_user')])]"/>
It makes more sense to use `knowledge.group_document_user` because that's the minimum level of the knowledge app.

2019-06-19 14:42 UTC, ivantodorovich approved these changes

2019-06-19 14:47 UTC, max3903 approved these changes

2019-06-19 15:07 UTC, pedrobaeza commented
/ocabot merge

2019-06-19 15:47 UTC, merged