[13.0][MIG] mig_document_url : Migration to 13.0
OCA/knowledge pull request #243
Opened 2020-03-11 10:09 UTC by manuelcalerosolis

This is the migration of mig_document_url to v 13.0

@Tecnativa TT19733

2020-03-11 10:16 UTC, manuelcalerosolis commented
Ready to be reviewed @pedrobaeza @ernestotejeda @chienandalu 
Please review

2020-03-25 16:39 UTC, ernestotejeda reviewed
Generate readme

2020-03-25 16:39 UTC, ernestotejeda commented on document_url/__manifest__.py
> +    "author": "Tecnativa," "Odoo Community Association (OCA)",
```suggestion
    "author": "Tecnativa, Odoo Community Association (OCA)",
```

2020-03-25 16:53 UTC, ernestotejeda reviewed
Functional review: OK
Looks very nice, jeje

2020-03-25 16:56 UTC, ernestotejeda requested changes

2020-03-25 16:56 UTC, ernestotejeda commented on document_url/wizard/document_url.py
> +class AddUrlWizard(models.Model):
```suggestion
class AddUrlWizard(models.TransientModel):
```

2020-04-15 10:58 UTC, chienandalu requested changes
Thanks, @manuelcalerosolis :) Did you attend @ernestotejeda remarks

2020-04-15 10:58 UTC, chienandalu commented on document_url/__manifest__.py
> +#                       Pedro M. Baeza <pedro.baeza@serviciosbaeza.com>
Please, update Pedro's author lines
```suggestion
# Copyright 2014-20 Tecnativa - Pedro M. Baeza
```

2020-04-15 11:14 UTC, chienandalu requested changes
Functional test ok :) Attend comments to unblock the PR :)

2020-04-16 11:54 UTC, Tardo requested changes
Looks good! only one non-blocking comment...

2020-04-16 11:54 UTC, Tardo commented on document_url/view/document_url_view.xml
> +        <field name='type'>ir.actions.act_window</field>
:fire:
It's the default value

2020-04-23 06:32 UTC, chienandalu commented on document_url/security/ir.model.access.csv
> +access_ir_attachment_add_url,access_ir_attachment_add_url,model_ir_attachment_add_url,,1,1,1,1
```log
2020-04-22 14:55:50,976 158 WARNING openerp_test odoo.modules.loading: The transient model ir.attachment.add_url (Wizard to add URL attachment) should not have explicit access rules!
```

2020-10-22 11:54 UTC, flachica commented
I need this module. I will open new PR.

2020-11-05 15:20 UTC, victoralmau commented
Please, @joao-p-marques, @chienandalu , @Tardo, @ernestotejeda review it again

2020-11-05 15:44 UTC, ernestotejeda reviewed
Code review: :+1: 
Regenerate the readme

2020-11-05 15:46 UTC, victoralmau approved these changes

2020-11-05 16:05 UTC, ernestotejeda approved these changes
Functional review: :+1:

2020-11-06 07:23 UTC, joao-p-marques approved these changes
LGTM :+1:

2020-11-10 08:42 UTC, pedrobaeza commented
/ocabot merge nobump

2020-11-10 10:29 UTC, merged