[MIG] document_url: Migration to 15.0
OCA/knowledge pull request #353
Opened 2022-06-16 17:18 UTC by matiasperalta1

2022-06-28 15:14 UTC, HaraldPanten approved these changes
Functional review

2022-07-17 18:24 UTC, pedrobaeza requested changes
See this image for my comments:

![Selección_007](https://user-images.githubusercontent.com/7165771/179419576-5f7dc477-ce22-49a5-bb61-83b5d52722d9.png)

You can compare with the module in v14:

![Selección_009](https://user-images.githubusercontent.com/7165771/179419583-8d8f12d3-7eec-4f96-a96f-46e924888573.png)

2022-07-18 17:38 UTC, matiasperalta1 commented
@victoralmau Hi Victor. I contact you to ask you a question for this module. I'm migrating this module to v15 and I have seen that some changes were made by you in the migration to v14. I am trying to use the mimetype "application/link" but it is not working for me because I think it is invalid. How have you made it work? 
Thank you very much and I hope your answer.

2022-07-18 17:47 UTC, victoralmau commented
Hi, the approach is correct. I think the first thing to do is to add all the changes from v14 to the commit history. These changes are explained in the v14 migration PR: https://github.com/OCA/knowledge/pull/306

2022-07-20 07:09 UTC, pedrobaeza commented
/ocabot migration document_url

2022-07-20 07:11 UTC, pedrobaeza commented
Everything is working now except having "Add attachments" and "Add URL" in 2 lines instead of one. Can you please check it?

2022-07-20 07:12 UTC, pedrobaeza commented
> The migration issue (#308) has been updated to reference the current pull request. however, a previous pull request was referenced : #337. Perhaps you should check that there is no duplicate work. CC : @JoelZilli

@legalsylvain it seems the new check is not correct, as the referenced PR is closed

2022-07-20 07:15 UTC, victoralmau requested changes
Hi, thanks for the work.

- Do not delete `url.js` file, make the necessary changes to reduce diff in commit
- Squash administrative commits

Except for the comment in https://github.com/OCA/knowledge/pull/353#issuecomment-1189912542, everything would be correct.

2022-07-24 10:16 UTC, pedrobaeza commented
Pre-commit is failing.

2022-07-25 13:52 UTC, matiasperalta1 commented
@pedrobaeza Pre-commit Fixed

2022-07-25 14:03 UTC, pedrobaeza approved these changes

2022-07-25 14:04 UTC, pedrobaeza commented
Thanks for the contribution

/ocabot merge nobump

2022-07-25 14:09 UTC, merged