[15.0] [IMP] document_url: upload url from upload activity
OCA/knowledge pull request #421
Opened 2023-07-14 15:29 UTC by EmilioPascual

If you create upload activity, button to upload url appears

@Moduon MT-3175 @yajo @shide @rafaelbn

2023-07-17 06:33 UTC, yajo requested changes
I noticed that when you upload a document, the activity is set as done. However, when you add an URL, it isn't. I think the workflow should be the same, isn't it?

2023-07-17 06:33 UTC, yajo commented on document_url/static/src/xml/url.xml
> +                <i class="fa fa-plus-square" /> Add URL</button>
I think this is clearer.

```suggestion
                <i class="fa fa-link" /> Link document by URL</button>
```

2023-07-17 12:29 UTC, yajo approved these changes
Good now. Please squash to merge. Thanks!

2023-07-17 13:02 UTC, rafaelbn approved these changes
Great improvement 👍🏼 😄 

Please squash and if possible add a simple GIF to show new feature

2023-07-17 14:42 UTC, EmilioPascual commented
Squash done.
Gif:
![ezgif com-video-to-gif (1)](https://github.com/OCA/knowledge/assets/53056345/9e4b2c17-aae1-4517-bc01-9717af84e1db)

2023-07-18 10:17 UTC, yajo commented
/ocabot merge minor

2023-07-18 10:21 UTC, merged