[17.0][MIG] document_page_approval: Migration to 17.0
OCA/knowledge pull request #509
Opened 2024-11-12 09:46 UTC by victoralmau

Supersedes https://github.com/OCA/knowledge/pull/498

Migration to 17.0

Changes done:
- [x] Squash administrative commits
- [x] Purge translations
- [x] Remove `ir.model.access.csv` file https://github.com/OCA/knowledge/pull/498#discussion_r1832184917
- [x] Improve tests (change to setUpClass)
- [x] `document_page`: Replace `name_get()` to `_compute_display_name()` https://github.com/OCA/knowledge/pull/498#discussion_r1832179917

@Tecnativa TT51529

2024-11-12 11:05 UTC, pilarvargas-tecnativa commented on document_page_approval/views/document_page_approval.xml
> +                <field name="approved_uid" readonly="1" />
Are all these new readonly needed?

2024-11-12 12:43 UTC, pilarvargas-tecnativa approved these changes
Code review :+1:

2024-11-12 14:20 UTC, max3903 commented
/ocabot migration document_page_approval

2024-11-12 14:20 UTC, max3903 commented
/ocabot migration document_page_approval

2024-11-12 14:22 UTC, max3903 approved these changes

2024-11-12 15:33 UTC, carlos-lopez-tecnativa requested changes

2024-11-12 15:33 UTC, carlos-lopez-tecnativa commented on document_page_approval/models/document_page.py
> +        context = literal_eval(action["context"])
![image](https://github.com/user-attachments/assets/11b2ae43-4d56-4bc6-9a98-aa1811ab0a83)

2024-11-12 17:25 UTC, carlos-lopez-tecnativa approved these changes

2024-11-12 19:51 UTC, pedrobaeza commented
/ocabot merge nobump

2024-11-13 06:35 UTC, pedrobaeza commented
/ocabot merge nobump

2024-11-13 06:39 UTC, merged